theme: jekyll-theme-minimal
title: Karan Chaudhari's Portfolio
description: Hello, my name is Karan Chaudhari. I am a freshman that is currently attending South Brunswick High School. I love to play tennis and drawing landscapes.
